defaults:
  - benchmark_schema   # use BenchmarkConfig class as defaults
  - _self_             # then fill in the rest of the args with below

output_filename: "/grand/insitu/cohanlon/alcf_kan_inr/result.csv"
data_path: "/grand/insitu/cohanlon/datasets/raw/test"
num_workers: 3    # num_processes_used = # gpus available x (1 + num_workers)
save_model: False
enable_pbar: False    # progress bar written to error on PBS

# Model(s)
model_types: ["mlp", "f-kan"]
mlp_params:
  - n_neurons: 64
    n_hidden_layers: 3
  - n_neurons: 32
    n_hidden_layers: 3
  - n_neurons: 16
    n_hidden_layers: 3
  - n_neurons: 8
    n_hidden_layers: 3
kan_params:
  - n_neurons: 64
    n_hidden_layers: 3
  - n_neurons: 32
    n_hidden_layers: 3
  - n_neurons: 16
    n_hidden_layers: 3
  - n_neurons: 8
    n_hidden_layers: 3

# Training
batch_size: 32768
num_epochs: 16

