defaults:
  - benchmark_schema   # use BenchmarkConfig class as defaults
  - _self_             # then fill in the rest of the args with below

home_dir: "/grand/insitu/cohanlon"
params_file: "alcf_kan_inr/params.json"
data_path: "datasets/raw"
num_workers: 0    # num_processes_used = # gpus available x (1 + num_workers)
save_model: False
enable_pbar: False    # progress bar written to error on PBS

# Model(s) to benchmark
model_types: ["mlp", "kan"]

# Training
batch_size: 32768

