defaults:
  - benchmark_schema   # use BenchmarkConfig class as defaults
  - _self_             # then fill in the rest of the args with below

home_dir: "/grand/insitu/cohanlon"

# relative to home directory
params_file: "alcf_kan_inr/params.json"
data_path: "datasets/raw"

num_workers: 8
pin_memory: True
prefetch_factor: 4
enable_pbar: True    # progress bar is written to error file on PBS
repeats: 5

save_mode: "largest" # save smallest or largest hashtable size for a given dataset INR

# Model(s) to benchmark
model_types: ["kan", "mlp"]
